title: Laman Muka BlankOn
author: BlankOn Developer

navbar-links:
  Beranda: "#BERANDA"
  Tentang: "#TENTANG"
  Fitur: "#FITUR"
  Pemasangan: "#PEMASANGAN"
  Unduh: "#UNDUH"
  Sponsor: "#SPONSOR"
  Menjadi Sponsor: "/menjadi-sponsor.html"
  Bergabung: "https://github.com/BlankOn/wiki/blob/master/Memulai.md"

timezone: "Asia/Jakarta"
markdown: kramdown
highlighter: rouge
permalink: /blog/:year/:title/
paginate: 5

kramdown:
  input: GFM

exclude:
  - CHANGELOG.md
  - CNAME
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
